[package]
name = "hardy-bpa"
description = "A BPv7 DTN Bundle process agent"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "hardy-bpa"
path = "src/main.rs"

[features]
default = ["sqlite-storage", "localdisk-storage"]
sqlite-storage = ["dep:hardy-sqlite-storage"]
localdisk-storage = ["dep:hardy-localdisk-storage"]
packaged-installation = []

[dependencies]
hardy-bpa-core = { path = "../bpa-core" }
hardy-cbor = { path = "../cbor" }
hardy-proto = { path = "../proto" }
hardy-sqlite-storage = { path = "../sqlite-storage", optional = true }
hardy-localdisk-storage = { path = "../localdisk-storage", optional = true }
tokio = { version = "1.36.0", features = ["macros","rt-multi-thread","signal"] }
tokio-util = "0.7.10"
tonic = "0.11.0"
config = { version = "0.14.0", features = ["toml"] }
serde = { version = "1.0.197", features = ["derive"] }
getopts = "0.2.21"
simplelog = "0.12.2"
log_err = "1.1.1"
log = "0.4.21"
directories = "5.0.1"
anyhow = "1.0.81"
time = { version = "0.3.34", features = ["macros"] }
crc = "3.0.1"
rand = "0.8.5"
cfg-if = "1.0.0"
base64 = "0.22.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-log = "0.2.0"

[build-dependencies]
built = "0.7.1"
