[package]
name = "hardy-bpa"
version = "0.1.0"
edition.workspace = true

[[bin]] # Bin to run the HelloWorld gRPC server
name = "bpa-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.14"
tonic = "0.11.0"
config = "0.14.0"
hardy-proto = { path = "../proto" }
