[package]
name = "hardy-bpa"
description = "A BPv7 DTN Bundle process agent"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "hardy-bpa"
path = "src/main.rs"

[features]
default = ["sqlite-storage", "localdisk-storage"]
sqlite-storage = ["dep:hardy-sqlite-storage"]
localdisk-storage = ["dep:hardy-localdisk-storage"]

[dependencies]
tokio = { version = "1.36.0", features = ["macros","rt-multi-thread","signal"] }
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tonic = "0.11.0"
config = { version = "0.14.0", features = ["toml"] }
hardy-bpa-core = { path = "../bpa-core" }
hardy-cbor = { path = "../cbor" }
hardy-proto = { path = "../proto" }
hardy-sqlite-storage = { path = "../sqlite-storage", optional = true }
hardy-localdisk-storage = { path = "../localdisk-storage", optional = true }
serde = { version = "1.0.197", features = ["derive"] }
getopts = "0.2.21"
simplelog = "0.12.2"
log_err = "1.1.1"
log = "0.4.21"
directories = "5.0.1"
atoi = "2.0.0"
sha1 = "0.10.6"
thiserror = "1.0.58"
anyhow = "1.0.81"

[build-dependencies]
built = "0.7.1"
