[package]
name = "hardy-bpa"
description = "A BPv7 DTN Bundle process agent"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "bpa-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.36.0", features = ["macros","rt-multi-thread","signal"] }
tokio-stream = "0.1.14"
tonic = "0.11.0"
config = { version = "0.14.0", features = ["toml"] }
hardy-proto = { path = "../proto" }
serde = { version = "1.0.197", features = ["derive"] }
getopts = "0.2.21"
simplelog = "0.12.2"
log_err = "1.1.1"
log = "0.4.21"
tokio-util = "0.7.10"

[build-dependencies]
built = "0.7.1"
