[package]
name = "hardy-bpa"
description = "A BPv7 DTN Bundle process agent"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "hardy-bpa"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.36.0", features = ["macros","rt-multi-thread","signal","fs"] }
tokio-stream = "0.1.14"
tonic = "0.11.0"
config = { version = "0.14.0", features = ["toml"] }
hardy-proto = { path = "../proto" }
serde = { version = "1.0.197", features = ["derive"] }
getopts = "0.2.21"
simplelog = "0.12.2"
log_err = "1.1.1"
log = "0.4.21"
tokio-util = "0.7.10"
directories = "5.0.1"
rusqlite = { version = "0.31.0", features = ["bundled"] }
atoi = "2.0.0"
sha1 = "0.10.6"
thiserror = "1.0.58"
rand = "0.8.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2.153"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[build-dependencies]
built = "0.7.1"
regex = "1.10.3"
atoi = "2.0.0"
sha1 = "0.10.6"
base64 = "0.22.0"
