[package]
name = "hardy-localdisk-storage"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["mmap"]
mmap = ["dep:memmap2"]

[dependencies]
hardy-bpa-core = { path = "../bpa-core" }
serde = { version = "1.0.197", features = ["derive"] }
anyhow = "1.0.81"
tokio = { version = "1.36.0", features = ["rt-multi-thread","fs"] }
rand = "0.8.5"
config = "0.14.0"
directories = "5.0.1"
memmap2 = { version = "0.9.4", optional = true }
time = "0.3.34"

[target.'cfg(unix)'.dependencies]
libc = "0.2.153"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[build-dependencies]
built = "0.7.1"
