[workspace]
resolver = "2"
members = [
    "bpa", 
    "bpa-core",
    "cbor", 
    "cbor/fuzz",
    "localdisk-storage",
    "proto", 
    "sqlite-storage",
    "trace-err"
]

[workspace.package]
edition = "2021"
