[workspace]
resolver = "2"
members = [
    "bpa",
    "bpa-api",
    "bpv7",
    "bpv7/fuzz",
    "cbor",
    "cbor/fuzz",
    "localdisk-storage",
    "proto",
    "sqlite-storage",
    "tcpcl",
]

[workspace.package]
edition = "2021"
