[package]
name = "hardy-sqlite-storage"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
hardy-bpa-core = { path = "../bpa-core" }
hardy-cbor = { path = "../cbor" }
rusqlite = { version = "0.31.0", features = ["bundled","time"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
thiserror = "1.0.58"
anyhow = "1.0.81"
serde = { version = "1.0.197", features = ["derive"] }
config = "0.14.0"
directories = "5.0.1"
base64 = "0.22.0"
time = "0.3.34"

[build-dependencies]
built = "0.7.1"
regex = "1.10.3"
sha1 = "0.10.6"
base64 = "0.22.0"