[package]
name = "hardy-bpv7"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
hardy-cbor = { path = "../cbor" }
thiserror = "1.0.61"
tracing = "0.1.40"
config = { version = "0.14.0", features = ["toml"] }
time = "0.3.36"
async-trait = "0.1.80"
sha2 = "0.10.8"
base64 = "0.22.1"
regex = "1.10.4"
urlencoding = "2.1.3"
crc = "3.2.1"

[dev-dependencies]
hex-literal = "0.4.1"
