[package]
name = "hardy-proto"
version = "0.1.0"
edition.workspace = true

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[dependencies]
bytes = "1.5.0"
prost = "0.12.3"
prost-types = "0.12.3"
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11"
