[package]
name = "hardy-bpa-core"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
hardy-cbor = { path = "../cbor" }
anyhow = "1.0.81"
crc = "3.0.1"
log = "0.4.21"
config = { version = "0.14.0" }
tokio-util = "0.7.10"